zephyrCommon: Add tone and noTone
zephyrproject-rtos/gsoc-2022-arduino-core pull request #100
Opened 2024-06-06 14:30 UTC by Ayush1325

- Add implementation of tone and noTone
- Add sample
- Tested on bcf

2024-06-09 11:50 UTC, soburi requested changes

2024-06-09 11:50 UTC, soburi commented on samples/blinky_tone/README.rst
> +Blinky Tone
Although the LED is available in common,
the purpose of this API is to play a sound, so it's not a good choice.
You should add Kconfig to make it possible to select the pin.
(Since you can't specify a symbolic name in Kconfig, I think you'll need to receive a numeric number like CONFIG_TONE_OUT_DIGITAL_PIN_NUMBER and resolve it like so with UTIL_CAT(D, ...).)
I think it's best to set the default to pin D8, which is used in the Arduino example.

2024-06-09 12:08 UTC, Ayush1325 commented on samples/blinky_tone/README.rst
> +Blinky Tone
I think it would be better to copy https://docs.arduino.cc/built-in-examples/digital/toneMelody/ example. However, I do not have a piezo buzzer and thus cannot really test it. So, wouldn't it be better to remove the example from this PR and do that separately?

2024-06-10 00:04 UTC, soburi commented on samples/blinky_tone/README.rst
> +Blinky Tone
> I think it would be better to copy https://docs.arduino.cc/built-in-examples/digital/toneMelody/ example. 

https://github.com/arduino/arduino-examples/blob/main/examples/02.Digital/toneMelody/toneMelody.ino

The code is in the public domain so that you can import it with a license notice.
But even so, It is better to modify to make a pin configurable.

> However, I do not have a piezo buzzer and thus cannot really test it. So, wouldn't it be better to remove the example from this PR and do that separately?

If you can't test, you don't have the hardware, describe how to verify the code and notice it in the commit message.

2024-06-10 10:38 UTC, Ayush1325 commented on samples/blinky_tone/README.rst
> +Blinky Tone
@soburi What do you mean by import with license notice?

2024-06-10 16:41 UTC, Ayush1325 commented
Found a piezo buzzer and tested with bcf. Also fixed the case for frequency = 0.

2024-06-10 16:44 UTC, DhruvaG2000 requested changes

2024-06-10 16:44 UTC, DhruvaG2000 commented on samples/tone_melody/src/pitches.h
> +/*************************************************
Missing licenses

2024-06-10 16:44 UTC, DhruvaG2000 commented on samples/tone_melody/src/main.cpp
> +    tone(CONFIG_TONE_OUT_DIGITAL_PIN_NUMBER, melody[thisNote], noteDuration);
I honestly don't think this is the way to go. I don't want to go and look at a Kconfig option just to see which pin  is being used. A sample should be self contained and easy to read IMO.

I'd rather simply:
```
#define toneOutPin 8

tone(toneOutPin , melody[thisNote], noteDuration);
```
Or something similar.

2024-06-10 16:44 UTC, DhruvaG2000 commented on samples/tone_melody/src/pitches.h
> +/*************************************************
I see it got resolved now. ignore this.

2024-06-10 16:49 UTC, Ayush1325 commented
@DhruvaG2000 What should I do regarding copyright and license?

2024-06-14 10:48 UTC, soburi commented on samples/blinky_tone/README.rst
> +Blinky Tone
I think it is enough because it describes the code from where.

https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/pull/100/files#diff-d26d067fb4bf1ed2b5f8429f6cfa7b9020e323c7d9f29c4f121199f4e17506d0R20

2024-06-14 10:49 UTC, soburi commented on samples/tone_melody/src/main.cpp
> + * SPDX-License-Identifier: CC-BY-1.0
This is perhaps `CC0-1.0`.

2024-06-14 10:50 UTC, soburi commented on samples/tone_melody/src/main.cpp
> + *
Add your credit if it is modified.

2024-06-25 17:18 UTC, DhruvaG2000 requested changes

2024-06-25 17:18 UTC, DhruvaG2000 commented on cores/arduino/main.cpp
> +    k_yield();
None of you commits even talk about this change, and it feels unrelated to this PR.
k_can_yield maybe a better option, but something to discuss beyond the scope of this PR.

2024-06-26 12:01 UTC, DhruvaG2000 commented on samples/tone_melody/src/main.cpp
> + * SPDX-License-Identifier: CC0-1.0
This seems like a very liberal license: https://creativecommons.org/publicdomain/zero/1.0/deed.en

> You can copy, modify, distribute and perform the work, even for commercial purposes, all without asking permission. See Other Information below.
> When using or citing the work, you should not imply [endorsement ](https://creativecommons.org/publicdomain/zero/1.0/deed.en#ref-endorsement)by the author or the affirmer.


I think best to remove it from here and make this file in this context as Zephyr dictates, Apache 2. I am also okay with not having this sample at all if it creates licensing issues, we can always only point to it's link in documentation (with changes required if any).

@soburi  thoughts?

2024-06-29 15:31 UTC, Ayush1325 commented
@DhruvaG2000 I think it might be best to remove the example from this PR. The upstream example can be used without any modification, so it is not particularly important to have it here, especially blocking this PR.

2024-06-30 10:45 UTC, soburi commented on samples/tone_melody/src/main.cpp
> + * SPDX-License-Identifier: CC0-1.0
License changes can only be made by the copyright holder.
In this case, since we are not the authors of this sample, we need to either inherit the original license or not use this sample.
It's not a complex sample, so it might be best to recreate it.

2024-06-30 13:23 UTC, Ayush1325 commented on samples/tone_melody/src/main.cpp
> + * SPDX-License-Identifier: CC0-1.0
I have dropped the sample from this PR.

2024-06-30 13:31 UTC, DhruvaG2000 approved these changes
I Am ok with this.

2024-06-30 20:53 UTC, soburi approved these changes

2024-07-01 05:19 UTC, merged