zephyrCommon: Implement pulseIn
zephyrproject-rtos/gsoc-2022-arduino-core pull request #101
Opened 2024-06-08 10:58 UTC by Ayush1325

- A basic sync implementation
- Max precision of millisec. The actual arduino API seems to want microsec precision.

2024-06-10 11:56 UTC, mathieuchopstm commented on cores/arduino/zephyrCommon.cpp
> +	delta = k_ticks_to_us_floor64(end) - k_ticks_to_us_floor64(start);
Calculating delta in ticks would reduce rounding errors (`delta = k_ticks_to_us_floor64(end - start);`)

2024-06-13 06:05 UTC, DhruvaG2000 requested changes

2024-06-13 06:05 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +
remove extra blank line

2024-06-13 06:05 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +	while(gpio_pin_get_dt(spec) != state);
There's no timeout logic?

2024-06-13 07:55 UTC, Ayush1325 commented on cores/arduino/zephyrCommon.cpp
> +	while(gpio_pin_get_dt(spec) != state);
Right, I forgot to add that.

2024-06-13 08:27 UTC, Ayush1325 commented on cores/arduino/zephyrCommon.cpp
> +	while(gpio_pin_get_dt(spec) != state);
I have added a simple timer-based implementation.

2024-06-19 13:19 UTC, DhruvaG2000 requested changes
Mostly looks good, with the minor suggestions we should be ok.

2024-06-19 13:19 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +#endif
I know we've missed adding this in the past, but please add a comment to identify the endif:
```
// CONFIG_GPIO_GET_DIRECTION
```

2024-06-19 13:19 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +      goto cleanup;
Here and everywhere else above, I am not a big fan of using goto's inside while loops please.

2024-06-19 13:19 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +      goto cleanup;
I'd rather you break the loop and then add a conditional goto cleanup outside it.

2024-06-19 14:06 UTC, Ayush1325 commented
@DhruvaG2000 Any idea regarding the failing CI?

2024-06-19 14:08 UTC, DhruvaG2000 commented
> @DhruvaG2000 Any idea regarding the failing CI?

Yep, locally reproduced just now.
``/__w/gsoc-2022-arduino-core/gsoc-2022-arduino-core/Arduino-Zephyr-API/samples/i2cdemo/prj.conf:2: warning: attempt to assign the value 'y' to the undefined symbol CPLUSPLUS``

Need to get rid of this symbol from everywhere looks like.

2024-06-19 14:09 UTC, DhruvaG2000 commented
Not related to this PR, so nothing to be alarmed.

2024-06-19 14:16 UTC, DhruvaG2000 commented
This PR should probably help:
https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/pull/104

2024-06-19 15:46 UTC, DhruvaG2000 approved these changes

2024-06-19 15:46 UTC, merged