zephyrCommon: Implement random and randomSeed
zephyrproject-rtos/gsoc-2022-arduino-core pull request #102
Opened 2024-06-08 10:59 UTC by Ayush1325

- Using zephyr random api
- Using a stub for randomSeed since it is not present in Zephyr

2024-06-09 12:01 UTC, soburi requested changes

2024-06-09 12:01 UTC, soburi commented on cores/arduino/zephyrCommon.cpp
> +	sys_rand_get(&temp, sizeof(temp));
Since Zephyr's random numbers behave differently depending on the backend, you should use the original ANSI C rand() or an equivalent linear congruential implementation here.

2024-06-11 14:48 UTC, Ayush1325 commented on cores/arduino/zephyrCommon.cpp
> +	sys_rand_get(&temp, sizeof(temp));
@DhruvaG2000 Do you have any input regarding this? I am fine with adding ANSI C implementation if that would be better. We would probably need to document somewhere that we are not using zephyr random implementation though.

2024-06-12 03:29 UTC, DhruvaG2000 requested changes

2024-06-12 03:29 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +void randomSeed(unsigned long) {}
Let's take inspiration from how esp32 is doing it here:
https://github.com/espressif/arduino-esp32/blob/master/cores/esp32/WMath.cpp

2024-06-12 03:29 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +	sys_rand_get(&temp, sizeof(temp));
> // Calling randomSeed() will force the
> // Pseudo Random generator like in

See if we can do something like the esp32 arduino core is doing.

2024-06-12 18:00 UTC, Ayush1325 commented
I have switched to using zephyr stdlib `rand` and `srand`.

2024-06-13 11:24 UTC, DhruvaG2000 approved these changes

2024-06-13 16:30 UTC, soburi approved these changes

2024-06-14 06:12 UTC, merged