Add SPI Library
zephyrproject-rtos/gsoc-2022-arduino-core pull request #103
Opened 2024-06-12 17:38 UTC by Ayush1325

- Tested master mode on beagleconnect freedom.
- Add master sample.
- Interrupts not implemented. Slave mode not tested.
- Fixes #87

2024-06-13 06:27 UTC, DhruvaG2000 requested changes

2024-06-13 06:27 UTC, DhruvaG2000 commented on libraries/SPI/SPI.cpp
> +uint8_t SPCR = 0;
No need of ``= 0`` IMO
See https://stackoverflow.com/questions/16015656/are-global-variables-always-initialized-to-zero-in-c

2024-06-13 06:27 UTC, DhruvaG2000 commented on libraries/SPI/SPI.cpp
> +uint8_t SPCR = 0;
Also, may want to add a comment at the top saying
```
/* Serial Peripheral Control Register */
```
As some people may even call it SPIGCR or something else. 
See https://ti.com/lit/ug/sprugp2a/sprugp2a for eg.

2024-06-13 06:27 UTC, DhruvaG2000 commented on libraries/SPI/SPI.cpp
> +  int ret;
No mixed declarations please.
FYI: https://langdev.stackexchange.com/questions/3115/why-are-mixed-declarations-more-challenging-to-implement-than-forcing-all-declar

2024-06-13 06:27 UTC, DhruvaG2000 commented on libraries/SPI/SPI.cpp
> +
remove extra blank lines

2024-06-13 06:27 UTC, DhruvaG2000 commented on samples/spi_master/README.rst
> +SPI Master
Please make use of more inclusive terminology.  This should be addressed throughout this PR.
Read https://www.oshwa.org/a-resolution-to-redefine-spi-signal-names/

SPI controller makes more sense.

2024-06-13 06:27 UTC, DhruvaG2000 commented on samples/spi_master/src/app.cpp
> +#define SS 3
Very ambiguous name, use something more verbose

2024-06-13 07:39 UTC, Ayush1325 commented on samples/spi_master/src/app.cpp
> +#define SS 3
So, the reason for choosing `SS` is that it seems to be defined in standard arduino as the CS Pin.

2024-06-13 07:42 UTC, Ayush1325 commented on libraries/SPI/SPI.cpp
> +uint8_t SPCR = 0;
@DhruvaG2000 the name is taken from [Arduino SPI docs](https://docs.arduino.cc/tutorials/generic/introduction-to-the-serial-peripheral-interface/). So I think we should stick with it?

2024-06-13 07:53 UTC, Ayush1325 commented on libraries/SPI/SPI.cpp
> +  int ret;
@DhruvaG2000 Do you just mean moving `ret` at the top or remove mixed declaration (like C89)? That would require making everything non-const.

2024-06-13 09:11 UTC, DhruvaG2000 commented on libraries/SPI/SPI.cpp
> +  int ret;
just move it to the top.

2024-06-13 09:12 UTC, DhruvaG2000 commented on libraries/SPI/SPI.cpp
> +uint8_t SPCR = 0;
@Ayush1325  My comment wasn't on the name, I'm just saying write the full form as a comment above

2024-06-13 09:13 UTC, DhruvaG2000 commented on samples/spi_master/src/app.cpp
> +#define SS 3
https://docs.arduino.cc/tutorials/generic/introduction-to-the-serial-peripheral-interface/

chip sel/ CS makes more sense.

2024-06-13 09:14 UTC, DhruvaG2000 commented on samples/spi_master/src/app.cpp
> +#define SS 3
> Controller/peripheral is formerly known as master/slave. Arduino no longer supports the use of this terminology. See the table below to understand the new terminology

2024-06-25 16:58 UTC, DhruvaG2000 approved these changes
I think we'll also have to add the spi node to add support for other platforms as well, but I don't suppose you'd have the hw to test it all anyway.
So I am good with this PR, thanks for addressing all concerns!

2024-06-26 12:02 UTC, merged