libraries: SPI: Hanlde multiple Wire instances
zephyrproject-rtos/gsoc-2022-arduino-core pull request #113
Opened 2024-08-04 04:48 UTC by soburi

Create multiple SPI instance if spis array contains plural elements. Declare these as 'SPI1', 'SPI2', ..., from second element of the array. (First element is already declare as 'SPI'.)

2024-08-06 05:35 UTC, DhruvaG2000 requested changes

2024-08-06 05:35 UTC, DhruvaG2000 commented on libraries/SPI/SPI.cpp
> +#endif // HAS_PORP(i2cs)
Pardon me, I didn't understand how I2C has any relevance here in SPI.cpp?

2024-08-06 05:35 UTC, DhruvaG2000 commented on libraries/SPI/SPI.cpp
> +/* If i2cs node is not defined, tries to use arduino_i2c */
`s/arduino_i2c/arduino_spi` ?

2024-08-06 06:24 UTC, soburi commented on libraries/SPI/SPI.cpp
> +#endif // HAS_PORP(i2cs)
Sorry, I verified the code but forgot to edit the comment. I'm using the structure that was originally used for I2C.

2024-08-06 06:24 UTC, soburi commented on libraries/SPI/SPI.cpp
> +/* If i2cs node is not defined, tries to use arduino_i2c */
Fixed it. Thanks.

2024-08-06 06:33 UTC, soburi commented
I'm going to put it back into draft because I have some concerns. Sorry.

2024-08-17 14:32 UTC, DhruvaG2000 reviewed
@soburi  nothing against this PR, but can you add more in your commit about how this change helps us/ what feature it enables? Talk about what enhancement this is bringing in basically.

2024-08-17 14:33 UTC, DhruvaG2000 commented
Also, `s/Hanlde/handle` in $subject

2024-08-17 20:13 UTC, Ayush1325 reviewed
LGTM

2024-08-17 20:13 UTC, Ayush1325 commented on libraries/SPI/SPI.cpp
> +#elif DT_NODE_EXISTS(DT_NODELABEL(arduino_spi))
So where does the `arduino-spi` name come from? Are any boards already defining it using that label?

2024-08-17 22:24 UTC, soburi commented on libraries/SPI/SPI.cpp
> +#elif DT_NODE_EXISTS(DT_NODELABEL(arduino_spi))
It is usually define with `arduino_header` in `zephyr/boards` definitions.
This line is intended to take advantage of it if it is already defined.
And we can override with overlay in this package with defining `spis` property.

2024-08-18 00:35 UTC, soburi commented
@DhruvaG2000 

> @soburi nothing against this PR, but can you add more in your commit about how this change helps us/ what feature it enables? Talk about what enhancement this is bringing in basically.

Added description to commit message. 

> Also, s/Hanlde/handle in $subject

Fixed it. Thank you.

2024-08-18 09:05 UTC, DhruvaG2000 commented
> > Also, s/Hanlde/handle in $subject
> 
> Fixed it. Thank you.

@soburi  Nope, I still see the wrong spelling in subject. https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/pull/113/commits

2024-08-18 09:06 UTC, DhruvaG2000 requested changes

2024-08-18 09:06 UTC, DhruvaG2000 commented on libraries/SPI/SPI.h
> +
Please fix above checkpatch warns @soburi .

>  WARNING: please, no spaces at the start of a line

2024-08-28 04:14 UTC, DhruvaG2000 requested changes

2024-08-28 04:14 UTC, DhruvaG2000 commented on libraries/SPI/SPI.h
> +
Was this fixed?
Can you please fix, rebase and force push if not done?

2024-08-30 13:28 UTC, DhruvaG2000 approved these changes

2024-08-30 13:28 UTC, merged