Implement interrupts and noInterrupts
zephyrproject-rtos/gsoc-2022-arduino-core pull request #119
Opened 2024-08-16 09:13 UTC by Ayush1325

- Using irq_lock and irq_unlock zephyr apis.
- Not really sure where these should go. `Common.h` has the following line:
```
// interrupts() / noInterrupts() must be defined by the core
```
- Need these for the [NeoPixel library](https://github.com/adafruit/Adafruit_NeoPixel).

2024-08-16 10:02 UTC, soburi commented on cores/arduino/zephyrCommon.cpp
> +static unsigned int irq_key = UINT_MAX;
Please put it into an anonymous namespace that is started from line 13,
or redeclare here.

2024-08-17 14:49 UTC, DhruvaG2000 requested changes

2024-08-17 14:49 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +static unsigned int irq_key = UINT_MAX;
I am no big fan of `UINT_MAX` , is there an alternate approach we can use here?
AFAICS I don't see a similar implementation of lock/ unlock anywhere in zephyr, that checks against something like UINT_MAX. This feels error prone to me.

2024-08-17 14:49 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +    irq_key = irq_lock();
I don't fully understand from the documentation what possible values of key are. Do you know? Maybe we can rely on those than uint max?

2024-08-17 20:01 UTC, Ayush1325 commented on cores/arduino/zephyrCommon.cpp
> +    irq_key = irq_lock();
So the docs just say that the values will be arch specific. We can use a bool flag or a `std::optional` instead to keep track if the `irq_lock` was already acquired.

2024-08-18 09:03 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +    irq_key = irq_lock();
@Ayush1325  if bool works, then I'd go with bool.

2024-08-18 14:22 UTC, DhruvaG2000 requested changes
You have defined `interrupts()` / `noInterrupts()` only in `common.cpp`. How will anyone outside of this file ever use it? Using it in some example would be great.

These function prototypes don't exist in the Arduino Core API.
See how SAMD has done it: https://github.com/arduino/ArduinoCore-samd/blob/993398cb7a23a4e0f821a73501ae98053773165b/cores/arduino/Arduino.h#L53

2024-08-18 15:40 UTC, Ayush1325 commented
> You have defined `interrupts()` / `noInterrupts()` only in `common.cpp`. How will anyone outside of this file ever use it? Using it in some example would be great.
> 
> These function prototypes don't exist in the Arduino Core API. See how SAMD has done it: https://github.com/arduino/ArduinoCore-samd/blob/993398cb7a23a4e0f821a73501ae98053773165b/cores/arduino/Arduino.h#L53

Is there a reason to use macro instead of just adding function prototype to `Arduino.h`?

2024-08-18 15:42 UTC, DhruvaG2000 commented
> > You have defined `interrupts()` / `noInterrupts()` only in `common.cpp`. How will anyone outside of this file ever use it? Using it in some example would be great.
> > These function prototypes don't exist in the Arduino Core API. See how SAMD has done it: https://github.com/arduino/ArduinoCore-samd/blob/993398cb7a23a4e0f821a73501ae98053773165b/cores/arduino/Arduino.h#L53
> 
> Is there a reason to use macro instead of just adding function prototype to `Arduino.h`?

Nope, not atall. I just meant to show that they have exposed it via the `Arduino.h`. You can make it a prototype.

2024-08-18 15:44 UTC, DhruvaG2000 approved these changes
Thanks for addressing all comments.

2024-08-28 04:12 UTC, DhruvaG2000 commented
Can you please rebase and force push?

2024-08-30 13:29 UTC, merged