Arduino.h: Add digitalPinToInterrupt
zephyrproject-rtos/gsoc-2022-arduino-core pull request #121
Opened 2024-09-02 13:09 UTC by Ayush1325

- Return the same number as long as not more than number of digital pins.
- This does not seem to be present in ArduinoCoreAPI but defined for all Arduino boards (and microblocks has started using it).
- Also present in arduino docs [1]

[1]: https://www.arduino.cc/reference/en/language/functions/external-interrupts/digitalpintointerrupt/

2024-09-04 08:05 UTC, DhruvaG2000 requested changes

2024-09-04 08:05 UTC, DhruvaG2000 commented on cores/arduino/Arduino.h
> +static inline int digitalPinToInterrupt(pin_size_t pin)
I think this is a very surface level implementation we have done here, I don't think it's quite accurate? I maybe wrong.

> See [attachInterrupt()](https://www.arduino.cc/reference/en/language/functions/external-interrupts/attachinterrupt) for a full list of supported interrupt pins on all boards.

Can you not check whether the pin supports interrupt or not? The current implementation just feels like it's returning pin if it exists, nothing to do with whether it supports IRQ.

2024-09-05 12:12 UTC, Ayush1325 commented
I tried putting it in the anonymous namespace, but then I got undefined reference errors. So not sure if `interrupts` and `noInterrupts` are working or not.

Note: I am not a C++ dev and have never used namespaces anything newer than C++98. So my understanding here is rather limited.

2024-09-15 06:34 UTC, DhruvaG2000 approved these changes

2024-09-15 06:34 UTC, merged