Add multi thread Example
zephyrproject-rtos/gsoc-2022-arduino-core pull request #13
Opened 2022-07-09 18:24 UTC by DhruvaG2000

- Demonstrate that direct zephyr calls can be made even with the Arduino API in use.
- Examples shows concurrency by async blinking of 3 LEDs

Signed-off-by: Dhruva Gole <goledhruva@gmail.com>

2022-07-30 05:15 UTC, szczys requested changes

2022-07-30 05:15 UTC, szczys commented on examples/arduino-threads/README.rst
> +- ``blink1()`` controls ``led1`` and has a 1000ms sleep cycle
This should be updated to explain all 3 LED (built-in, D10, D11) and the role of the Loop.

2022-07-30 05:15 UTC, szczys commented on examples/arduino-threads/README.rst
> +:ref:`BOARD.dts file <devicetree-in-out-files>`.
Is this still correct? It looks like the code is using pin numbers (which is great!) but this references device tree alias'

2022-07-31 07:45 UTC, DhruvaG2000 commented
I again rebased the `dev` on top of this branch 🤦🏼 
Now this has added all latest commits from main into this branch showing too many unnecessary files changes. I am closing this PR and creating a different branch and will cherrypick the useful commits there.

2022-07-31 16:05 UTC, closed without merging