start writing Documentation
zephyrproject-rtos/gsoc-2022-arduino-core pull request #20
Opened 2022-08-02 06:25 UTC by DhruvaG2000

Signed-off-by: Dhruva Gole <goledhruva@gmail.com>

2022-08-31 12:21 UTC, beriberikix commented
I think we should add a link to the documentation folder from the README.

2022-08-31 12:30 UTC, DhruvaG2000 commented
>  I think we should add a link to the documentation folder from the README.


Done.

2022-09-01 18:54 UTC, szczys requested changes

2022-09-01 18:54 UTC, szczys commented on README.md
> +Arduino Core API module for zephyr leverages the power of Zephyr under an Arduino-C++ style abtraction layer thus helping zephyr new-comers to start using it without worrying about learning about new
```suggestion
Arduino Core API module for zephyr leverages the power of Zephyr under an Arduino-C++ style abtraction layer thus helping zephyr new-comers to start using it without worrying about learning about new APIs and libraries. See the project documentation folder for detailed documentation on these topics:

* [Using external Arduino Libraries](/documentation/arduino_libs.md)
* [Adding board variantks](/documentation/overlays.md)
* [Adding custom boards](/documentation/variants.md)
```

The documentation folder doesn't have a README.md which means linking to it won't render a page. This might be a confusing user experience so I suggest linking explicitly to the available pages.

2022-09-01 18:54 UTC, szczys commented on documentation/arduino_libs.md
> +For example refer to the ADXL345 demo has ``ADXL345.cpp`` in it's CMakeLists.
```suggestion
For example, we add `target_sources(app PRIVATE src/ADXL345.cpp)`  to CMakeLists.txt.
```
I think being explicit on how to add the source file to the build will be helpful.

2022-09-01 18:54 UTC, szczys commented on documentation/variants.md
> +   └── arduino_nano_33_ble_pinmap.h
```suggestion
├── arduino_nano_33_ble
│   ├── arduino_nano_33_ble.overlay
│   └── arduino_nano_33_ble_pinmap.h
├── CMakeLists.txt
└── variants.h

```

I think CMakeLists and variants.h should be shown in this tree view.

2022-09-01 18:54 UTC, szczys commented on documentation/variants.md
> +- You need to satisfy all requirements mentioned in the project's README.
This is confusing. Maybe remove Pre-reqs and just write a summary paragraph that indicates:

1. Boards already supported by Zephyr can be added to the variants folder as outlined in this documentation
2. Custom boards can first by added by following [the official Zephyr porting guide](https://docs.zephyrproject.org/latest/hardware/porting/board_porting.html). Once completed, continue here by adding a variant for your custom board.

2022-09-01 18:54 UTC, szczys commented on documentation/overlays.md
> +# How to add board variants
Do you think this file can be combined with variants.md?

2022-09-02 16:33 UTC, szczys approved these changes
Looks great, thanks for the changes!

2022-09-02 17:36 UTC, beriberikix approved these changes
Looks great!

2022-09-02 17:37 UTC, merged