zephyrCommon: Implement attachInterrupt()/detachInterrupt()
zephyrproject-rtos/gsoc-2022-arduino-core pull request #51
Opened 2022-09-19 05:15 UTC by soburi

This implementation depends on CONFIG_GPIO_GET_CONFIG
to keep the GPIO state already configured by pinMode().

2022-09-19 05:17 UTC, soburi commented
I'm testing with nrf52840 with this patch https://github.com/soburi/zephyr/tree/nrfx_gpio_get_config
(This patch needs more verification.)

2022-09-25 09:21 UTC, DhruvaG2000 requested changes

2022-09-25 12:34 UTC, soburi commented on samples/attach_interrupt/prj.conf
> +CONFIG_CPLUSPLUS=y
Removed CONFIG_CPLUSPLUS and CONFIG_GPIO.

2022-09-25 13:59 UTC, DhruvaG2000 requested changes

2022-09-25 13:59 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +void pinModeImpl(pin_size_t pinNumber, gpio_flags_t pinmode, voidFuncPtr callback, gpio_flags_t intmode)
It seems like this PR is doing much more than just Implementing attachInterrupt()/detachInterrupt, and thus in my opinion deserves to have it's own commit that separates the modifications that have been made in the way that pinMode was earlier implemented.

2022-09-25 14:01 UTC, DhruvaG2000 commented on cores/arduino/zephyrCommon.cpp
> +void pinModeImpl(pin_size_t pinNumber, gpio_flags_t pinmode, voidFuncPtr callback, gpio_flags_t intmode)
Also if possible, the commit message should justify the use of new pinMode being better than earlier one and also the addition of ``GPIO_MODE_MASK`` instead of directly using each individual ``GPIO_XX`` flag as and when required?

2022-10-12 10:59 UTC, soburi commented on cores/arduino/zephyrCommon.cpp
> +void pinModeImpl(pin_size_t pinNumber, gpio_flags_t pinmode, voidFuncPtr callback, gpio_flags_t intmode)
As a result of redesign, I was able to eliminate this.
It's just attachInterrupt/detachInterrupt and their internal implementation.

2022-10-12 11:02 UTC, soburi commented
@DhruvaG2000 

Redesign based on https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/pull/60.

2022-10-13 16:16 UTC, DhruvaG2000 commented
Any reason this is a draft PR? Please mark as ready if you want it to be reviewed,
Thanks.

2022-11-19 13:39 UTC, merged