zephyrCommon: Implement analogRead()/analogReference()
zephyrproject-rtos/gsoc-2022-arduino-core pull request #54
Opened 2022-09-23 06:40 UTC by soburi

The 'io-channels' node under the 'zephyr,user' defines
available ADC channels.

The 'io-channel-pins' defines the mapping of ADC channels
to pin numbers.  API looks up the 'io-channel-pins' when
querying the ADC channel by digital pin number.
So it should be in the same order as 'io-channels' node.

For original Arduino API compatibility, ADC resolution
should configure as 10-bit.

ADC that is on MCU supported by Zephyr exists
only 16-bit resolution currently.
So it supports resolutions up to 16-bit.

Signed-off-by: TOKITA Hiroshi <tokita.hiroshi@fujitsu.com>

2022-09-25 09:17 UTC, DhruvaG2000 reviewed
This PR adds a big chunk of code to overlay files, hence for adding further variants it maybe useful to have documentation for what all is needed to get analog working in these overlays.
Do you think you can also add documentation for the same?

2022-09-25 09:18 UTC, DhruvaG2000 requested changes

2022-09-25 09:18 UTC, DhruvaG2000 commented on samples/analog_input/prj.conf
> +CONFIG_ADC=y
I think all this can be shifted into the project's global KConfig

2022-09-25 13:10 UTC, DhruvaG2000 requested changes

2022-09-25 13:10 UTC, DhruvaG2000 commented on samples/analog_input/README.rst
> +Change ``arduino_nano_33_ble`` appropriately for other supported boards.
This README needs updating.

2022-09-25 13:48 UTC, soburi commented on samples/analog_input/prj.conf
> +CONFIG_ADC=y
Fixed it.

2022-09-25 15:14 UTC, soburi commented on samples/analog_input/README.rst
> +Change ``arduino_nano_33_ble`` appropriately for other supported boards.
I forgot it.😱

Update README did.

2022-09-26 04:03 UTC, soburi commented
@DhruvaG2000 
Rebase to newest main branch done.
Could you please review again?

2022-09-26 14:07 UTC, soburi commented
> Code looks good, but let me test this patch on real hardware before approving and merging.

Okay, No need to hurry

2022-10-01 07:04 UTC, DhruvaG2000 approved these changes
Built and tested on my arduino nano 33 ble sense, and it works OK.

2022-10-05 16:46 UTC, merged