variants: Introduce a digital-pins array to define digital pin
zephyrproject-rtos/gsoc-2022-arduino-core pull request #60
Opened 2022-10-10 07:36 UTC by soburi

The `d0-gpios` node format makes it difficult to handle
digital pin configuration from DTS macros.

Introduce the simple array `digital-pins` instead of `g0-gpios` to define digital pin
to GPIO port and pin mapping.

2022-10-13 16:23 UTC, DhruvaG2000 requested changes
Hi,
Thanks alot for this PR!
The idea here does help in making the code a lot more manageable by using arrays rather than hard coded vairables for each gpio, however build seems to fail :

```
-- Found devicetree overlay: /home/dhruva/zephyrproject/zephyr/../modules/lib/Arduino-Zephyr-API/variants/arduino_nano_33_iot/arduino_nano_33_iot.overlay
unit address and first address in 'reg' (0x6a) don't match for /soc/sercom@42001800/atecc608a@15
unit address and first address in 'reg' (0xa) don't match for /soc/adc@42004000/channel@10
unit address and first address in 'reg' (0xb) don't match for /soc/adc@42004000/channel@11
unit address and first address in 'reg' (0x12) don't match for /soc/adc@42004000/channel@18
unit address and first address in 'reg' (0x13) don't match for /soc/adc@42004000/channel@19
```
and also a lot of DT expansion errors that are likely due to some syntax issues.
Kindly fix this

2022-10-13 16:23 UTC, DhruvaG2000 commented on documentation/variants.md
> +		digital-pin-gpios = <&arduino_header 6 0>,	/* Digital */
this does seem like a good idea, thanks!

2022-10-13 22:12 UTC, soburi commented
> Hi, Thanks alot for this PR! The idea here does help in making the code a lot more manageable by using arrays rather than hard coded vairables for each gpio, however build seems to fail :
> 
> ```
> -- Found devicetree overlay: /home/dhruva/zephyrproject/zephyr/../modules/lib/Arduino-Zephyr-API/variants/arduino_nano_33_iot/arduino_nano_33_iot.overlay
> unit address and first address in 'reg' (0x6a) don't match for /soc/sercom@42001800/atecc608a@15
> unit address and first address in 'reg' (0xa) don't match for /soc/adc@42004000/channel@10
> unit address and first address in 'reg' (0xb) don't match for /soc/adc@42004000/channel@11
> unit address and first address in 'reg' (0x12) don't match for /soc/adc@42004000/channel@18
> unit address and first address in 'reg' (0x13) don't match for /soc/adc@42004000/channel@19
> ```
> 
> and also a lot of DT expansion errors that are likely due to some syntax issues. Kindly fix this

I created PR #63.

2022-10-14 02:09 UTC, DhruvaG2000 commented
> > Hi, Thanks alot for this PR! The idea here does help in making the code a lot more manageable by using arrays rather than hard coded vairables for each gpio, however build seems to fail :
> > ```
> > -- Found devicetree overlay: /home/dhruva/zephyrproject/zephyr/../modules/lib/Arduino-Zephyr-API/variants/arduino_nano_33_iot/arduino_nano_33_iot.overlay
> > unit address and first address in 'reg' (0x6a) don't match for /soc/sercom@42001800/atecc608a@15
> > unit address and first address in 'reg' (0xa) don't match for /soc/adc@42004000/channel@10
> > unit address and first address in 'reg' (0xb) don't match for /soc/adc@42004000/channel@11
> > unit address and first address in 'reg' (0x12) don't match for /soc/adc@42004000/channel@18
> > unit address and first address in 'reg' (0x13) don't match for /soc/adc@42004000/channel@19
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and also a lot of DT expansion errors that are likely due to some syntax issues. Kindly fix this
> 
> I created PR #63.

The issue is not only in nano 33 iot but others as well like ble and ble sense:
```
zephyr/devicetree.h:82:17: error: 'DT_N_S_zephyr_user' was not declared in this scope; did you mean 'DT_N_S_zephyr_user_ORD'?
   82 | #define DT_ROOT DT_N
      |                 ^~~~

```

Can you try building for each variant locally and check once?

2022-10-14 04:14 UTC, soburi commented
> The issue is not only in nano 33 iot but others as well like ble and ble sense:

I couldn't reproduce this issue.
Could you tell me using version and command line?

2022-10-14 14:23 UTC, DhruvaG2000 commented
> > The issue is not only in nano 33 iot but others as well like ble and ble sense:
> 
> I couldn't reproduce this issue with ble and ble sense. Could you tell me using version and command line?

I'm using zephyr sdk 0.15  and using the command:
``west build -p -b arduino_nano_33_ble_sense samples/blinky_arduino``

ditto same command works on my local main branch so I doubt that this could be an issue related to my zephyr version or wrong command.
Is there some config you have enabled that I maybe missing or some uncommitted changes?

2022-10-14 14:25 UTC, DhruvaG2000 commented
My bad, I had an unclean zephyr repo.
I cleaned up my local and it seems to work ok for nano ble and sense

2022-10-15 06:26 UTC, soburi commented
> and I see the errors all over again, can you check?

This PR is require [fdea3c9a ](https://github.com/zephyrproject-rtos/zephyr/commit/fdea3c9a44ef8b89e54cd5d46629513700f9ce5e) change.

I think it should better to track latest develpmenent branch if this repository plans to be a part of zephyrrtos.

2022-10-18 22:16 UTC, soburi commented
@DhruvaG2000 

https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/pull/63#issuecomment-1282454907

Done.

2022-10-19 23:00 UTC, soburi commented on documentation/variants.md
> +		digital-pin-gpios = <&arduino_header 6 0>,	/* Digital */
> -- Found devicetree overlay: /home/dhruva/zephyrproject/zephyr/../modules/lib/Arduino-Zephyr-API/variants/arduino_nano_33_iot/arduino_nano_33_iot.overlay
> unit address and first address in 'reg' (0x6a) don't match for /soc/sercom@42001800/atecc608a@15
> unit address and first address in 'reg' (0xa) don't match for /soc/adc@42004000/channel@10
> unit address and first address in 'reg' (0xb) don't match for /soc/adc@42004000/channel@11
> unit address and first address in 'reg' (0x12) don't match for /soc/adc@42004000/channel@18
> unit address and first address in 'reg' (0x13) don't match for /soc/adc@42004000/channel@19

It is solved by #63.

2022-10-24 13:53 UTC, DhruvaG2000 approved these changes
LGTM Code wise, need to test once on hardware.

2022-11-13 16:58 UTC, DhruvaG2000 commented
Sorry for the delay, Works on hardware too. merging, Thanks!

2022-11-13 16:58 UTC, merged