zephyrSerial: Redesign to supporting hardware serial
zephyrproject-rtos/gsoc-2022-arduino-core pull request #64
Opened 2022-10-15 06:13 UTC by soburi

Add support for the hardware serial device. The implementation
using the UART interrupt, enabling CONFIG_UART_INTERRUPT_DRIVEN.

Instantiate as 'Serial' with UART device defined in 'serials' array
under zephyr,user node. If the 'serials' array is not defined,
try to instantiate with a UART device labeled 'arduino_serial'.
If even  'arduino_serial' does not define, it uses the stub
implementation that redirects to printk().

---
As a result of this PR, changes Serial output goes to UART1(exporse in Arduino header)  in nrf52840dk_nrf52840 case.

2022-10-16 17:15 UTC, DhruvaG2000 requested changes
Thanks for this PR,
I feel like you also need to add overlay for ``nrf52840dk_nrf52840``, rest you've covered.

2022-10-16 17:15 UTC, DhruvaG2000 commented on samples/serial_event/README.rst
> +$> west flash --bossac=/home/$USER/.arduino15/packages/arduino/tools/bossac/1.9.1-arduino2/bossac
close code ticks after this .. ```

2022-10-16 23:28 UTC, soburi commented
> I feel like you also need to add overlay changes for `nrf52840dk_nrf52840`, rest you've covered.

It is no needed.
Because nrf52840dk_nrf52840 defines `arduino_serial`, uses it.
Use exists definition if possible to use. (It is rule for reduce our work.)

2022-10-16 23:59 UTC, soburi commented on samples/serial_event/README.rst
> +$> west flash --bossac=/home/$USER/.arduino15/packages/arduino/tools/bossac/1.9.1-arduino2/bossac
Fixed it.

2022-10-17 01:48 UTC, DhruvaG2000 approved these changes
Built locally, yet to test on HW, but code LGTM

2022-10-18 16:48 UTC, DhruvaG2000 commented
This is a major PR in serial, and it would be awesome to have @szczys review it as well.

2022-10-25 14:38 UTC, szczys approved these changes
I read through the commit and this LGTM. I didn't have the chance to do a deep dive into everything, @DhruvaG2000 do you have any remaining concerns with this PR?

2022-10-29 06:13 UTC, merged

2022-10-29 06:13 UTC, DhruvaG2000 commented
> do you have any remaining concerns with this PR?

None, Thanks alot @soburi for this PR and Mike for reviewing! Apologies for the delay in merging.