variants: Add cc3220sf
zephyrproject-rtos/gsoc-2022-arduino-core pull request #72
Opened 2023-04-15 08:44 UTC by DhruvaG2000

Add support for the TI [CC3220SF LaunchXL](https://www.ti.com/product/CC3200#software-development) platform

Closes https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/issues/35

2023-04-17 04:10 UTC, soburi commented on variants/cc3220sf_launchxl/cc3220sf_launchxl_pinmap.h
> +#define LED_BUILTIN 4
It is better to define in dts.

https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/blob/next/variants/arduino_nano_33_ble/arduino_nano_33_ble.overlay#L43

2023-04-17 14:15 UTC, soburi approved these changes

2023-04-17 14:18 UTC, soburi commented on variants/cc3220sf_launchxl/cc3220sf_launchxl.overlay
> +				<&gpioa1 2 0>,	/* I2C_SCL | YELLOW_LED */
Also good to add i2cs = <...>;

2023-04-17 16:32 UTC, soburi requested changes
https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/pull/72/files#r1168774695

2023-04-22 16:41 UTC, DhruvaG2000 commented on variants/cc3220sf_launchxl/cc3220sf_launchxl.overlay
> +				<&gpioa1 2 0>,	/* I2C_SCL | YELLOW_LED */
done

2023-04-22 16:41 UTC, DhruvaG2000 commented
> https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/pull/72/files#r1168774695

Major changes after force push:
* Use of boosterpack_header node in overlay (as we have followed for other arduino platforms in this project using their connectors nodes in overlays)
* Add serial and I2C node in overlay

2023-04-23 00:38 UTC, soburi approved these changes

2023-04-23 00:38 UTC, soburi commented
LGTM.

2023-05-01 10:55 UTC, merged