README: Update heading and also maintainers
zephyrproject-rtos/gsoc-2022-arduino-core pull request #73
Opened 2023-04-23 11:16 UTC by DhruvaG2000

* New maintainers including Dhruva and Tokita, Hiroshi have been added.
* The title has been updated to specify what the project does at the top of README.

2023-04-24 15:48 UTC, szczys approved these changes
I suggest that @DhruvaG2000 be listed at the top of the Maintainers list, followed by @soburi as the two of you are doing all the maintenance and development work.

LGTM!

2023-04-24 18:58 UTC, beriberikix commented
+1 adding them! Can we do it or do we need help from the Zephyr maintainers?

2023-04-24 20:39 UTC, alvarowolfx commented
Any reason why I'm being removed ? I keep following the project but I haven't seen anything that I was requested to review. There are any meetings happening yet related to the project ?

2023-04-26 03:15 UTC, beriberikix commented
Ah, I wasn't aware of that change. Can we add Alvaro back to the Maintainers?

2023-04-26 03:16 UTC, beriberikix commented on README.md
> -- [alvarowolfx](https://github.com/alvarowolfx)
Add back

2023-04-26 03:16 UTC, beriberikix requested changes
All looks good but please add Alvaro back.

2023-04-26 04:01 UTC, soburi commented
At the moment this repository is just a standalone repository, so I don't really care about the maintainer list.
But if we plan to put it under zephyr's governance, it's better to follow zephyr's rules.
zephyr clearly defines maintainers.


> Maintainer: lead Collaborators on an area identified by the TSC (e.g. Architecture, code subsystems, etc.). Maintainers shall also serve as the area’s representative on the TSC as needed. Maintainers may become voting members of the TSC under the guidelines stated in the project Charter.
> 
> Collaborator: A highly involved Contributor in one or more areas. May become a Maintainer with approval of existing TSC voting members.
> 
> Contributor: anyone in the community that contributes code or documentation to the project. Contributors may become Collaborators by approval of the existing Collaborators and Maintainers of the particular code base areas or subsystems.
> 

https://docs.zephyrproject.org/latest/project/project_roles.html#contributor

2023-04-26 13:41 UTC, beriberikix commented
Makes sense! But we're not suggesting making those changes at this moment. Let's add you and update Dhruva's role in the README and decide if we want to change processes in a future PR :)

2023-05-01 10:51 UTC, DhruvaG2000 commented on README.md
> -- [alvarowolfx](https://github.com/alvarowolfx)
Pardon deleting @alvarowolfx , I have added him back

2023-05-01 13:55 UTC, beriberikix approved these changes
LGTM. Thank you for continuing to develop this module!

2023-05-01 16:20 UTC, merged