variants: Add support for nRF9160
zephyrproject-rtos/gsoc-2022-arduino-core pull request #75
Opened 2023-08-04 14:14 UTC by ddeletic

2023-08-05 14:18 UTC, soburi requested changes

2023-08-05 14:18 UTC, soburi commented on variants/variants.h
> +	#include <arduino_nano_33_ble_pinmap.h>
Please do not change anything that is not related to the fix.

2023-08-05 14:18 UTC, soburi commented on variants/nrf9160dk_nrf9160/nrf9160dk_nrf9160_pinmap.h
> +#define NRF1960DK_NRF1960
I'm not recommended to include definitions unrelated to the Arduino API unless there is a specific reason.

2023-08-06 14:26 UTC, soburi approved these changes

2023-08-06 14:27 UTC, soburi commented
@DhruvaG2000 Could you take look at?

2023-08-06 14:44 UTC, DhruvaG2000 requested changes
One nit, otherwise looks okay!
Thanks alot for upstreaming this @ddeletic !

2023-08-06 14:44 UTC, DhruvaG2000 commented on variants/variants.h
> +	#include "nrf9160dk_nrf9160_pinmap.h"
please follow the coding pattern, no indent necessary here.

2023-08-06 14:44 UTC, DhruvaG2000 commented on variants/nrf9160dk_nrf9160/nrf9160dk_nrf9160.overlay
> +				low-power-enable;
Again, just curious, this property seems to be some sort of equivalent of isolating I/O's during low power mode?

2023-08-06 14:44 UTC, DhruvaG2000 commented on variants/nrf9160dk_nrf9160/nrf9160dk_nrf9160.overlay
> +			<&arduino_header 5 0>;
Just curious, Were you able to use and test the arduino analog read/write API support from this project?

2023-08-06 17:24 UTC, DhruvaG2000 requested changes
In this PR as well, please follow the [Zephyr Contribution Guidelines](https://docs.zephyrproject.org/latest/contribute/guidelines.html)

Commit title should look like:
```
variants: Add support for nRF9160
```
Along with some commit message and sign off.

2023-08-07 13:35 UTC, DhruvaG2000 approved these changes
LGTM!

2023-08-07 13:50 UTC, DhruvaG2000 commented on variants/variants.h
> +	#include "nrf9160dk_nrf9160_pinmap.h"
@ddeletic ,

> If you insist...
> 
> However, one of the most important aspects of software development is writing code that is easy to maintain. The first

Totally agree :)

> pre-requisite of maintainable code is that it is easy to read and understand. Now, this coding pattern
> 
> ```
> #ifdef CONFIG_BOARD_ARDUINO_NANO_33_BLE
> #include <arduino_nano_33_ble_pinmap.h>
> #endif // CONFIG_BOARD_ARDUINO_NANO_33_BLE
> #ifdef CONFIG_BOARD_ARDUINO_NANO_33_BLE_SENSE
> #include <arduino_nano_33_ble_sense_pinmap.h>
> #endif // CONFIG_BOARD_ARDUINO_NANO_33_BLE_SENSE
> #ifdef CONFIG_BOARD_ARDUINO_NANO_33_IOT
> #include <arduino_nano_33_iot_pinmap.h>
> #endif /* CONFIG_BOARD_ARDUINO_NANO_33_IOT */
> #ifdef CONFIG_BOARD_NRF52840DK_NRF52840
> #include "nrf52840dk_nrf52840_pinmap.h"
> #endif /* CONFIG_BOARD_NRF52840DK_NRF52840 */
> ...
> ```
> 
> does not fall into that category. I'm sure you'll agree that
> 
> ```
> #ifdef CONFIG_BOARD_ARDUINO_NANO_33_BLE
>     #include <arduino_nano_33_ble_pinmap.h>
> #endif // CONFIG_BOARD_ARDUINO_NANO_33_BLE
> #ifdef CONFIG_BOARD_ARDUINO_NANO_33_BLE_SENSE
>     #include <arduino_nano_33_ble_sense_pinmap.h>
> #endif // CONFIG_BOARD_ARDUINO_NANO_33_BLE_SENSE
> #ifdef CONFIG_BOARD_ARDUINO_NANO_33_IOT
>     #include <arduino_nano_33_iot_pinmap.h>
> #endif /* CONFIG_BOARD_ARDUINO_NANO_33_IOT */
> #ifdef CONFIG_BOARD_NRF52840DK_NRF52840
>     #include "nrf52840dk_nrf52840_pinmap.h"
> #endif /* CONFIG_BOARD_NRF52840DK_NRF52840 */
> ...
> ```
> 
> is much easier to follow.* 

NAK, if it were the case of simple `if()` statements you had my full support to indent. However when it comes to `#ifdef`s things are different. The general rule here is that one should write code "pretending" as though there was no #ifdef there.
They are just meant to remove / add pieces of code at compile time and play no real role in the logic itself in most cases.
Hence imagine this piece of code compiled,

```
 #ifdef CONFIG_BOARD_NRF52840DK_NRF52840
     #include "nrf52840dk_nrf52840_pinmap.h"
#endif /* CONFIG_BOARD_NRF52840DK_NRF52840 */
```

would look like:
```
     #include "nrf52840dk_nrf52840_pinmap.h"
```

The indent makes no sense in such a case right?

> You are probably thinking right now, who is this rude dude trampling over my code telling me it is no good. 

In the spirit of Open Source, I am always open to suggestions :) 

> That is definitely not my intention. But, from experience, I know that this sort of thing will never be done unless it is gradually improved, as we go along. After all, we are talking about white spaces...

As far as I have grepped in zephyr codebase, `rg -i "\#ifdef"` didn't lead me to the coding style you are suggesting above. Hence, I am only trying to stick as close as possible to what ZephyrProject follows 😄 

> 
> `*` The original pull request was written as above, with all include statements nested. However, @soburi requested that no changes are made that are not related to the pull request itself.

I agree with @soburi  here, unless there's some critical fix let's not touch code that isn't related to the purpose of this PR.

2023-08-07 13:51 UTC, merged