feat/i2c: Add I2C wrapper functions
zephyrproject-rtos/gsoc-2022-arduino-core pull request #8
Opened 2022-07-01 07:38 UTC by DhruvaG2000

* Tested with a custom example for ADXL345 which can be found [here](https://github.com/DhruvaG2000/Arduino-Core-Zephyr/pull/5#issuecomment-1166949394)

* Follows latest licensing and directory structure

* uses ringBuffer

* TODO: Testing for multiple byte read/write

* TODO: Add i2c example if required

Signed-off-by: Dhruva Gole <goledhruva@gmail.com>

2022-07-01 07:40 UTC, DhruvaG2000 commented
For historical discussion on implementing i2c please refer: https://github.com/DhruvaG2000/Arduino-Core-Zephyr/pull/5

2022-07-01 14:56 UTC, beriberikix approved these changes
Defer to others for technical review

2022-08-01 20:19 UTC, alvarowolfx requested changes
I had some issues with `I2C` not being enabled, so I had to manually add `CONFIG_I2C` to my `prj.conf` file. Also the Ring buffer API is not enabled by default, so I had to add `CONFIG_RING_BUFFER`

One thing that we can do is to add to the lib `Kconfig`, so those things are enabled by default.

```
config ARDUINO_I2C
	bool "ARDUINO_API"
	select RING_BUFFER	
	select I2C
	default y
```

Another thing that I added here as I was testing, was an implementation for the Arduino `millis` function. 

```
unsigned long millis() { 
  return k_uptime_get();
}
```

2022-08-01 20:19 UTC, alvarowolfx commented on libraries/Wire/Wire.cpp
> +}
We can implement this using memcpy to fill the txBuffer.
```
size_t arduino::ZephyrI2C::write(const uint8_t *buffer, size_t size) {  
  if (usedTxBuffer + size > 256) {
    size = 256 - usedTxBuffer;
  }
	memcpy(txBuffer + usedTxBuffer, buffer, size);
	usedTxBuffer += size;	
  return size;
}
```

2022-08-01 20:19 UTC, alvarowolfx commented on libraries/Wire/Wire.cpp
> +int arduino::ZephyrI2C::available() { // TODO
We can implement the `available` function by checking if the ring buffer is not empty.
```
int arduino::ZephyrI2C::available() { 
  return !ring_buf_is_empty(&rxRingBuffer.rb);
}
```

2022-08-01 20:19 UTC, alvarowolfx commented on libraries/Wire/Wire.cpp
> +  if (ring_buf_peek(&rxRingBuffer.rb, buf, 1) > 0) {
We can change to use the internal `available` function

```
if (available() > 0) {
```

2022-08-01 20:19 UTC, alvarowolfx commented on libraries/Wire/Wire.cpp
> +  return rxBuffer[0];
I think this should return `0` as we don't have data available in this case here.

2022-08-01 20:19 UTC, alvarowolfx commented on libraries/Wire/Wire.cpp
> +int arduino::ZephyrI2C::peek() { return 1; }   // TODO
`peek` can be implemented using the ring buffer peek function like you used before on the read function
```
int arduino::ZephyrI2C::peek() { 
  uint8_t buf[1];
  int bytes_read = ring_buf_peek(&rxRingBuffer.rb, buf, 1);
  if (bytes_read == 0){
    return 0;
  } 
  return (int)buf[0]; 
}
```

2022-08-01 20:19 UTC, alvarowolfx commented on libraries/Wire/Wire.h
> +  uint8_t txBuffer[256], rxBuffer[256];
We can remove this `rxBuffer` as we are using a Ring Buffer from zephyr.

2022-08-01 20:20 UTC, alvarowolfx commented
I tested this branch with the changes that I sent here using a BH1750 sensor and this library - https://github.com/claws/BH1750

The only change that I had to make to the BH1750 lib was to replace the `Serial.println` with `printk` statements as we don't support `Serial` yet.

![Screen Shot 2022-08-01 at 16 13 36](https://user-images.githubusercontent.com/1615543/182239620-950c6627-feee-44c0-9957-cc64d82adc79.png)

2022-08-29 16:42 UTC, closed without merging