Add support for beagleconnect_freedom
zephyrproject-rtos/gsoc-2022-arduino-core pull request #92
Opened 2024-05-11 13:46 UTC by Ayush1325

- Test blinky_arduino
- Test hello_arduino

Not sure how I should number the mikrobus digital pins (or if I even should).

2024-05-12 12:09 UTC, DhruvaG2000 requested changes

2024-05-12 12:09 UTC, DhruvaG2000 commented on variants/beagleconnect_freedom/variants.h
> +/* All the pins that are 100 + x are gpio1 pins and < 100 are in gpio0 */
This comment doesn't make sense anymore and needs to be cleaned up.
It seems to be a remnant of commit e8e3c6294 ("restruct: add variants folder")

2024-05-12 12:09 UTC, DhruvaG2000 commented on variants/beagleconnect_freedom/beagleconnect_freedom.overlay
> +		builtin-led-gpios = <&gpio0 18 GPIO_ACTIVE_HIGH>;	/*  2.4GHz TX/RX  */
You  can also add a ``adc-pin-gpios =    `` right?

2024-05-12 12:09 UTC, DhruvaG2000 commented on variants/beagleconnect_freedom/beagleconnect_freedom.overlay
> +		i2cs = <&i2c0>;
Also missing ``pwms = `` ?

2024-05-12 16:18 UTC, Ayush1325 commented on variants/beagleconnect_freedom/beagleconnect_freedom.overlay
> +		builtin-led-gpios = <&gpio0 18 GPIO_ACTIVE_HIGH>;	/*  2.4GHz TX/RX  */
`adc-pin-gpios` is supposed to be defined for analog input pins. The pins in bcf are for mikrobus connector. So it would only make sense to add `adc-pin-gpios` if we are adding `digital-pin-gpios` as well. The reason for omission is that I am not sure how to name them since they are not really arduino header (or even numbered).

2024-05-12 16:23 UTC, Ayush1325 commented on variants/beagleconnect_freedom/beagleconnect_freedom.overlay
> +		i2cs = <&i2c0>;
I am not sure if anything is supposed to go into pwms for bcf? I modeled the overlay after `cc3220sf_launchxl` which also does not contain `pwms`. The device tree for bcf also does not seem to have any pwm nodes.

2024-05-12 18:08 UTC, DhruvaG2000 commented on variants/beagleconnect_freedom/beagleconnect_freedom.overlay
> +		i2cs = <&i2c0>;
I was just looking at https://www.mikroe.com/img/cms/mikrobus-image-1.jpg hence wondered if we need pwm, but if zephyr itself doesn't support pwm for beagleconnect today then ok to skip.

2024-05-12 18:11 UTC, DhruvaG2000 requested changes
One small request, can you also please update https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/blob/next/documentation/variants.md ?

2024-05-12 19:14 UTC, Ayush1325 commented
> One small request, can you also please update https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/blob/next/documentation/variants.md ?

Hi. I have added beagleconnect freedom to supported list. However, it seems that the supported list is outdated and some of the planned boards are also already supported.
Would you like me to edit those in this PR as well or is something missing. Alternatively I can create a new PR for that (or you can add them yourself later).

2024-05-13 05:40 UTC, DhruvaG2000 approved these changes
LGTM, Will update the supported variants list later on... This much is good for now.

2024-05-13 07:33 UTC, merged

2024-05-14 16:33 UTC, jadonk commented on variants/beagleconnect_freedom/beagleconnect_freedom.overlay
> +		builtin-led-gpios = <&gpio0 18 GPIO_ACTIVE_HIGH>;	/*  2.4GHz TX/RX  */
Why not all the other digital pins? 

https://openbeagle.org/beagleconnect/zephyr/arduino-core/-/commit/1ce0b0bfca16ffc9eb781f263525347e0b42cef5