beagleconnect_freedom: Add digital, analog, pwm pins
zephyrproject-rtos/gsoc-2022-arduino-core pull request #94
Opened 2024-05-14 17:07 UTC by Ayush1325

- Add pin layout described here: https://openbeagle.org/beagleconnect/zephyr/arduino-core/-/commit/1ce0b0bfca16ffc9eb781f263525347e0b42cef5
- Also remove LED_BUILTIN. Seems the dts entry is sufficient.

2024-05-14 17:09 UTC, Ayush1325 commented
Cc: @jadonk

2024-05-14 17:12 UTC, DhruvaG2000 requested changes
@Ayush1325 The commit message feels inadequate to me:

> - Add pin layout described here:
https://openbeagle.org/beagleconnect/zephyr/arduino-core/-/commit/1ce0b0bfca16ffc9eb781f263525347e0b42cef5


You need to add reasoning as to why it was chosen the way it is. Is there any pinout or diagram somewhere that can justify this mapping?

2024-05-14 17:13 UTC, DhruvaG2000 commented
My main concern here is a person comin new to the platform should be able to quickly make sense of what pin mapping you've created

2024-05-14 17:14 UTC, jadonk commented
Thanks. Looks good to me. Do you have a test procedure?

2024-05-14 17:20 UTC, Ayush1325 commented
> Thanks. Looks good to me. Do you have a test procedure?

Can you provide some clarification regarding how the pin numbering was chosen. Analog numbering seems simple but not sure about digital pin order.

2024-05-15 14:33 UTC, jadonk commented
> > Thanks. Looks good to me. Do you have a test procedure?
> 
> Can you provide some clarification regarding how the pin numbering was chosen. Analog numbering seems simple but not sure about digital pin order.

Sure.

I looked around for some examples of Arduino Click Shields such that Arduino examples that used mikroBUS boards might "just work", but I found that there wasn't much consistency between the Shields. I chose what I thought was both reasonably popular, affordable and included a reasonably good set of pins and documentation.

I want with [MikroE Arduino MKR Click Shield](https://www.mikroe.com/arduino-mkr-click-shield)

![image](https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/assets/9018/8f71b318-7d2c-42b4-b12d-5320526382d2)

![image](https://github.com/zephyrproject-rtos/gsoc-2022-arduino-core/assets/9018/0ed087c8-5153-451e-82da-f080f9a0afb4)

I tried to match up the equivalent Arduino pin with the pins on the 2 mikroBUS ports on BeagleConnect Freedom. My thinking was that if it worked on an Arduino MKR with the MikroE Arudino MKR Click Shield, then it should work with BeagleConnect Freedom. That should provide a great test resource.

Can you add this information to the documentation in a reasonable way?

2024-05-18 16:24 UTC, Ayush1325 commented
@jadonk Thanks for the input. I do not think there is any board specific docs currently, but we can certainly add a section in our own docs regarding this. 

@DhruvaG2000 I think this provides the context for the pin layout?

2024-05-18 18:27 UTC, DhruvaG2000 approved these changes
Yep, looks good now.

2024-05-18 18:28 UTC, merged